apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    # 主节点MySQL的配置文件
    [mysqld]
    # 使用二进制日志文件的方式进行主从复制，这是一个标准的设置
    log-bin
  replica.cnf: |
    # 从节点MySQL的配置文件
    [mysqld]
    # 代表的是从节点会拒绝除了主节点的数据同步操作之外的所有写操作，即：它对用户是只读的
    super-read-only