# Headless Service。类似绑定了mysql-0的IP地址
# 通过为 Pod 分配 DNS 记录来固定它的拓扑状态，比如“mysql-0.mysql”和“mysql-1.mysql”这样的 DNS 名字
# 其中，编号为 0 的节点就是我们的主节点
# 写请求，则必须直接以 DNS 记录的方式访问到 MySQL 的主节点
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
# 常规的 Service。用于负载均衡
# 所有用户的读请求，都必须访问第二个 Service 被自动分配的 DNS 记录
# 即：“mysql-read”（当然，也可以访问这个 Service 的 VIP）
# 读请求就可以被转发到任意一个 MySQL 的主节点或者从节点上
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql